services:
    DomainDrivenBundle\Routing\ContextRouteLoader:
        arguments:
            $contextDir: '%domain_driven.directories.context%'
            $configDir: '%domain_driven.directories.infrastructure%/%domain_driven.directories.config%'
            $fileName: '%domain_driven.files.routes%'
        tags: [routing.loader]
