services:
    DomainDrivenBundle\Routing\ContextRouteLoader:
        arguments:
            - '%kernel.project_dir%/%domain_driven.directories.context%'
            - '%domain_driven.directories.infrastructure%/%domain_driven.directories.config%'
            - '%domain_driven.files.routes%'
        tags: [routing.loader]
